include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy

variables:
    GIT_SUBMODULE_STRATEGY: normal

flatpak:master:
    extends: .flatpak
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: test
    variables:
        BUNDLE: "gnome-books-dev.flatpak"
        MANIFEST_PATH: "flatpak/org.gnome.Books.json"
        #MESON_ARGS: "-Dprofile=development"
        FLATPAK_MODULE: "gnome-books"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Books"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak:master']
    needs: ['flatpak:master']
